services:
  postgres:
    image: postgres:17
    container_name: pg17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rcms_database
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
