name: Restaurant Chain Management System CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Get the code
    - name: Get my code
      uses: actions/checkout@v4
    
    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    # Step 3: Install backend packages
    - name: Install backend stuff
      working-directory: ./backend
      run: npm install
    
    # Step 4: Test backend
    - name: Test backend
      working-directory: ./backend
      run: npm test