name: Restaurant Chain Management System CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Get my code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install backend stuff
      working-directory: ./backend
      run: npm install
    
    - name: Test backend
      working-directory: ./backend
      run: npm test

  frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Get my code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install frontend stuff
      working-directory: ./frontend
      run: npm install

    - name: Build frontend stuff
      working-directory: ./frontend
      run: npm run build